-- [[ Configure Treesitter ]]
---@diagnostic disable-next-line: missing-fields
require('nvim-treesitter.configs').setup({
  ensure_installed = {
    'asm',
    'bash',
    'bibtex',
    'c',
    'comment',
    'cpp',
    'css',
    'csv',
    'diff',
    'dockerfile',
    'git_config',
    'git_rebase',
    'gitattributes',
    'gitcommit',
    'gitignore',
    'go',
    'gomod',
    'gosum',
    'gowork',
    'gpg',
    'html',
    'java',
    'javascript',
    'jq',
    'jsdoc',
    'json',
    'jsonc',
    'just',
    'latex',
    'lua',
    'luadoc',
    'luap',
    'make',
    'markdown',
    'markdown_inline',
    'nix',
    'objdump',
    'pem',
    'php',
    'python',
    'query',
    'ruby',
    'rust',
    'sql',
    'sxhkdrc',
    'toml',
    'tsx',
    'typescript',
    'typst',
    'vim',
    'vimdoc',
    'yaml',
  },
  highlight = { enable = true },
  indent = { enable = true },
  playground = { enable = true },
})

-- vim: ts=2 sts=2 sw=2 et
